import pandas as pd
olist_customers_dataset = pd.read_csv('data/olist_customers_dataset.csv')
olist_geolocation_dataset = pd.read_csv('data/olist_geolocation_dataset.csv')
olist_order_items_dataset = pd.read_csv('data/olist_order_items_dataset.csv')
olist_order_payments_dataset = pd.read_csv('data/olist_order_payments_dataset.csv')
olist_order_reviews_dataset = pd.read_csv('data/olist_order_reviews_dataset.csv')
olist_orders_dataset = pd.read_csv('data/olist_orders_dataset.csv')
olist_products_dataset = pd.read_csv('data/olist_products_dataset.csv')
olist_sellers_dataset = pd.read_csv('data/olist_sellers_dataset.csv')
product_category_name_translation = pd.read_csv('data/product_category_name_translation.csv')

print(olist_customers_dataset.head())
print(olist_customers_dataset.columns)
print(olist_geolocation_dataset.head())
print(olist_geolocation_dataset.columns)
print(olist_order_items_dataset.head())
print(olist_order_items_dataset.columns)
print(olist_order_payments_dataset.head())
print(olist_order_payments_dataset.columns)
print(olist_order_reviews_dataset.head())
print(olist_order_reviews_dataset.columns)
print(olist_orders_dataset.head())
print(olist_orders_dataset.columns)
print(olist_products_dataset.head())
print(olist_products_dataset.columns)
print(olist_sellers_dataset.head())
print(olist_sellers_dataset.columns)
print(product_category_name_translation.head())
print(product_category_name_translation.columns)